server:
  port: 8080

spring:
  application:
    name: pricedrop-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/pricedrop

#  jackson:
#    serialization:
#      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data.mongodb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops
  endpoint:
    health:
      show-details: always

---

# Custom app configs
app:
  scheduler:
    enabled: true
    interval: 1800000   # 30 minutes in ms
  env: dev

  scraping:
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)
    timeout: 10000
    max-concurrency: 1
    request-delay-ms: 1500
    max-retries: 1
    captcha-cooldown-minutes: 30

  deals:
    limit: 10

affiliate:
  tag: keertiawast00-21